steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

# - id: "Chown em /var/www"
  # name: 'gcr.io/cloud_builders/docker'
  # args: ['exec', '-u', 'root', '-t', 'app', 'chown', '-R', 'www-data:www-data', '/var/www']

- id: "Rodando docker ps"
  name: 'gcr.io/cloud_builders/docker'
  args: ['ps']

# - id: "Rodando composer"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['exec', '-t', 'app', 'composer', 'install']

# - id: "Copiando .env"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['exec', '-t', 'app', 'cp', '/var/www/.env.example', '/var/www/.env']

# - id: "Rodando key:generate"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

# - id: "Rodando docker ps 2"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['ps']

# - id: "Rodando migrations"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

# - id: "Rodando phpunit"
#   name: 'gcr.io/cloud_builders/docker'
#   args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']