version: '3'

services:
    app:
        build: .
        container_name: app
        volumes:
            - ./laravel:/var/www
        networks: 
            - app_network
        depends_on: 
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: ./.docker/nginx/entrypoint.sh
        restart: always
        tty: true
        environment: 
            - NGINX_HOST=app
            - NGINX_PORT=9000
        ports:
            - "8000:80"
        volumes: 
            - ./laravel:/var/www
            - ./.docker/nginx:/var/www/.docker/nginx
        networks: 
            - app_network
        depends_on: 
            - app
    
    db:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - app_network

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - app_network

networks: 
    app_network:
        driver: bridge
